const DESCEIPTION = '\nEach new term in the Fibonacci sequence is generated by adding the previous two terms.'
    +'By starting with 1 and 2, the first 10 terms will be:\n'
+'\t1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n'
+ 'By considering the terms in the Fibonacci sequence whose values do not exceed four million,'
+'find the sum of the even-valued terms.';

// const main = (n) => {
//     if(n <= 1){
//         return n;
//     }
//     return main(n-1 ) + main(n-2);

// };

const main = n => {
    let fib = [];
    let arrUnder4mil = [];

    fib[0] = 1;
    fib[1] = 2;

    for(let i = 2; i <= 50; i++) {
        fib[i] = fib[i-2] + fib[i-1];
        fib.push(fib[i]);
    }

    for (let i = 0; i < fib.length; i++) {
        if (fib[i] <= n && fib[i] %2 == 0) {
            arrUnder4mil.push(fib[i]);
        }
    }

    return arrUnder4mil.reduce((a, b) => a + b, 0);
}
// PRINTS PROJECT DESCRIPTION
console.log(DESCEIPTION);
console.log('RESULT: ', main(4000000));
